[package]
name = "gridsolver"
version = "0.1.0"
authors = ["William Rieger <wrieger93@gmail.com>"]

[dependencies]
clap = "2.20.5"
env_logger = "0.4.2"
log = "0.3.7"
rand = "0.3"
try_from = "0.2.1"
unidecode = "0.3"
